export const AUTH_SET_SERVER_ADDRESS = 'AUTH_SET_SERVER_ADDRESS';
export const AUTH_SET_CURRENT_SITE = 'AUTH_SET_CURRENT_SITE';
export const AUTH_SET_SITES = 'AUTH_SET_SITES';

export const GLOBAL_SET_ERROR = 'GLOBAL_SET_ERROR';
export const GLOBAL_TOGGLE_LOADING = 'GLOBAL_TOGGLE_LOADING';

export const PAGES_TOGGLE_SUBITEMS = 'PAGES_TOGGLE_SUBITEMS';
export const PAGES_SAVE_ITEMS = 'PAGES_SAVE_ITEMS';
export const PAGES_SAVE_INITIAL_ITEMS = 'PAGES_SAVE_INITIAL_ITEMS';

export const WORKFLOWS_SAVE_ITEMS = 'WORKFLOWS_SAVE_ITEMS';
export const WORKFLOWS_UPDATE_ITEM = 'WORKFLOWS_UPDATE_ITEM';

export const SELECTEDITEM_SELECT_ITEM = 'SELECTEDITEM_SELECT_ITEM';
