export const AUTH_SET_SERVER_ADDRESS = 'AUTH_SET_SERVER_ADDRESS';
export const AUTH_SET_CURRENT_SITE = 'AUTH_SET_CURRENT_SITE';
export const AUTH_SET_SITES = 'AUTH_SET_SITES';

export const GLOBAL_SET_ERROR = 'GLOBAL_SET_ERROR';
export const GLOBAL_TOGGLE_LOADING = 'GLOBAL_TOGGLE_LOADING';

export const PAGES_TOGGLE_SUBITEMS = 'PAGES_TOGGLE_SUBITEMS';
export const PAGES_SAVE_PAGES = 'PAGES_SAVE_PAGES';
export const PAGES_SELECT_PAGE = 'PAGES_SELECT_PAGE';
export const PAGES_UPDATE_WORKFLOW_PAGE = 'PAGES_UPDATE_WORKFLOW_PAGE';
