import { PAGES_TOGGLE_SUBITEMS, PAGES_SAVE_PAGES, PAGES_SELECT_PAGE } from '../../actions/types';

const INIT_STATE = {
  publishedPages: {
      "150": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/",
        "DocumentChildrenIDs": [
          300,
          299,
          163,
          167,
          157,
          155,
          159,
          161,
          165,
          154,
          152,
        ],
        "DocumentID": 150,
        "DocumentName": "",
        "DocumentNamePath": "/",
        "open": true,
      },
      "152": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Campaign-assets",
        "DocumentChildrenIDs": [
          180,
        ],
        "DocumentID": 152,
        "DocumentName": "Campaign assets",
        "DocumentNamePath": "/Campaign assets",
        "open": false,
      },
      "154": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages",
        "DocumentChildrenIDs": [
          204,
          229,
          221,
          197,
          210,
          202,
          200,
          222,
          212,
          217,
          218,
          206,
          209,
          214,
          195,
          201,
          205,
        ],
        "DocumentID": 154,
        "DocumentName": "Special pages",
        "DocumentNamePath": "/Special pages",
        "open": false,
      },
      "155": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/About-Us",
        "DocumentChildrenIDs": [],
        "DocumentID": 155,
        "DocumentName": "About us",
        "DocumentNamePath": "/About us",
        "open": false,
      },
      "157": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Articles",
        "DocumentChildrenIDs": [
          169,
          172,
          177,
          175,
          171,
          178,
        ],
        "DocumentID": 157,
        "DocumentName": "Articles",
        "DocumentNamePath": "/Articles",
        "open": false,
      },
      "159": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes",
        "DocumentChildrenIDs": [
          194,
          192,
          190,
        ],
        "DocumentID": 159,
        "DocumentName": "Cafes",
        "DocumentNamePath": "/Cafes",
        "open": false,
      },
      "161": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Contact",
        "DocumentChildrenIDs": [
          182,
          185,
          187,
        ],
        "DocumentID": 161,
        "DocumentName": "Contact",
        "DocumentNamePath": "/Contact",
        "open": false,
      },
      "163": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/",
        "DocumentChildrenIDs": [],
        "DocumentID": 163,
        "DocumentName": "Home",
        "DocumentNamePath": "/Home",
        "open": false,
      },
      "165": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Partnership",
        "DocumentChildrenIDs": [],
        "DocumentID": 165,
        "DocumentName": "Partnership",
        "DocumentNamePath": "/Partnership",
        "open": false,
      },
      "167": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Store",
        "DocumentChildrenIDs": [
          226,
          231,
          225,
          224,
          228,
          227,
          181,
          179,
          188,
        ],
        "DocumentID": 167,
        "DocumentName": "Store",
        "DocumentNamePath": "/Store",
        "open": false,
      },
      "169": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Articles/Coffee-Beverages-Explained",
        "DocumentChildrenIDs": [],
        "DocumentID": 169,
        "DocumentName": "Coffee Beverages Explained",
        "DocumentNamePath": "/Articles/Coffee Beverages Explained",
        "open": false,
      },
      "171": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Articles/Coffee-processing-techniques",
        "DocumentChildrenIDs": [],
        "DocumentID": 171,
        "DocumentName": "Coffee processing techniques",
        "DocumentNamePath": "/Articles/Coffee processing techniques",
        "open": false,
      },
      "172": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Articles/Donate-with-us",
        "DocumentChildrenIDs": [],
        "DocumentID": 172,
        "DocumentName": "Donate with us",
        "DocumentNamePath": "/Articles/Donate with us",
        "open": false,
      },
      "175": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Articles/On-Roasts",
        "DocumentChildrenIDs": [],
        "DocumentID": 175,
        "DocumentName": "On Roasts",
        "DocumentNamePath": "/Articles/On Roasts",
        "open": false,
      },
      "177": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Articles/Origins-of-Arabica-Bourbon",
        "DocumentChildrenIDs": [],
        "DocumentID": 177,
        "DocumentName": "Origins of Arabica Bourbon",
        "DocumentNamePath": "/Articles/Origins of Arabica Bourbon",
        "open": false,
      },
      "178": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Articles/Which-brewing-fits-you",
        "DocumentChildrenIDs": [],
        "DocumentID": 178,
        "DocumentName": "Which brewing fits you?",
        "DocumentNamePath": "/Articles/Which brewing fits you?",
        "open": false,
      },
      "179": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Store/Checkout",
        "DocumentChildrenIDs": [
          270,
          268,
          269,
        ],
        "DocumentID": 179,
        "DocumentName": "Checkout",
        "DocumentNamePath": "/Store/Checkout",
        "open": false,
      },
      "180": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Campaign-assets/Cafe-promotion",
        "DocumentChildrenIDs": [
          286,
          294,
          295,
        ],
        "DocumentID": 180,
        "DocumentName": "Café promotion",
        "DocumentNamePath": "/Campaign assets/Café promotion",
        "open": false,
      },
      "182": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Contact/Boston",
        "DocumentChildrenIDs": [],
        "DocumentID": 182,
        "DocumentName": "HQ in North America",
        "DocumentNamePath": "/Contact/HQ in North America",
        "open": false,
      },
      "185": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Contact/London",
        "DocumentChildrenIDs": [],
        "DocumentID": 185,
        "DocumentName": "Office in Europe",
        "DocumentNamePath": "/Contact/Office in Europe",
        "open": false,
      },
      "187": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Contact/Sydney",
        "DocumentChildrenIDs": [],
        "DocumentID": 187,
        "DocumentName": "Office in Australia",
        "DocumentNamePath": "/Contact/Office in Australia",
        "open": false,
      },
      "188": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Store/Thank-you",
        "DocumentChildrenIDs": [],
        "DocumentID": 188,
        "DocumentName": "Thank you",
        "DocumentNamePath": "/Store/Thank you",
        "open": false,
      },
      "190": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/Australia",
        "DocumentChildrenIDs": [
          240,
          242,
          244,
        ],
        "DocumentID": 190,
        "DocumentName": "Australia",
        "DocumentNamePath": "/Cafes/Australia",
        "open": false,
      },
      "192": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/Europe",
        "DocumentChildrenIDs": [
          246,
          248,
          250,
          252,
          254,
        ],
        "DocumentID": 192,
        "DocumentName": "Europe",
        "DocumentNamePath": "/Cafes/Europe",
        "open": false,
      },
      "194": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/North-America",
        "DocumentChildrenIDs": [
          256,
          259,
          260,
          262,
          264,
          266,
        ],
        "DocumentID": 194,
        "DocumentName": "North America",
        "DocumentNamePath": "/Cafes/North America",
        "open": false,
      },
      "195": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/404",
        "DocumentChildrenIDs": [],
        "DocumentID": 195,
        "DocumentName": "404",
        "DocumentNamePath": "/Special pages/404",
        "open": false,
      },
      "197": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Address-detail",
        "DocumentChildrenIDs": [],
        "DocumentID": 197,
        "DocumentName": "Address detail",
        "DocumentNamePath": "/Special pages/Address detail",
        "open": false,
      },
      "200": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Change-password",
        "DocumentChildrenIDs": [],
        "DocumentID": 200,
        "DocumentName": "Change password",
        "DocumentNamePath": "/Special pages/Change password",
        "open": false,
      },
      "201": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Coffee-Club",
        "DocumentChildrenIDs": [],
        "DocumentID": 201,
        "DocumentName": "Coffee Club",
        "DocumentNamePath": "/Special pages/Coffee Club",
        "open": false,
      },
      "202": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Company-details",
        "DocumentChildrenIDs": [],
        "DocumentID": 202,
        "DocumentName": "Company details",
        "DocumentNamePath": "/Special pages/Company details",
        "open": false,
      },
      "204": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Generator",
        "DocumentChildrenIDs": [],
        "DocumentID": 204,
        "DocumentName": "Generator",
        "DocumentNamePath": "/Special pages/Generator",
        "open": false,
      },
      "205": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Machine-rental",
        "DocumentChildrenIDs": [],
        "DocumentID": 205,
        "DocumentName": "Machine rental",
        "DocumentNamePath": "/Special pages/Machine rental",
        "open": false,
      },
      "206": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Newsletter-subscription-confirmation",
        "DocumentChildrenIDs": [],
        "DocumentID": 206,
        "DocumentName": "Newsletter subscription confirmation",
        "DocumentNamePath": "/Special pages/Newsletter subscription confirmation",
        "open": false,
      },
      "209": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Newsletter-unsubscription-confirmation",
        "DocumentChildrenIDs": [],
        "DocumentID": 209,
        "DocumentName": "Newsletter unsubscription confirmation",
        "DocumentNamePath": "/Special pages/Newsletter unsubscription confirmation",
        "open": false,
      },
      "210": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Personal-details",
        "DocumentChildrenIDs": [],
        "DocumentID": 210,
        "DocumentName": "Personal details",
        "DocumentNamePath": "/Special pages/Personal details",
        "open": false,
      },
      "212": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Register",
        "DocumentChildrenIDs": [],
        "DocumentID": 212,
        "DocumentName": "Register",
        "DocumentNamePath": "/Special pages/Register",
        "open": false,
      },
      "214": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Search-Result",
        "DocumentChildrenIDs": [],
        "DocumentID": 214,
        "DocumentName": "Search result",
        "DocumentNamePath": "/Special pages/Search result",
        "open": false,
      },
      "217": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Sign-in",
        "DocumentChildrenIDs": [],
        "DocumentID": 217,
        "DocumentName": "Sign in",
        "DocumentNamePath": "/Special pages/Sign in",
        "open": false,
      },
      "218": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Thanks",
        "DocumentChildrenIDs": [],
        "DocumentID": 218,
        "DocumentName": "Thanks",
        "DocumentNamePath": "/Special pages/Thanks",
        "open": false,
      },
      "221": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Your-Account",
        "DocumentChildrenIDs": [],
        "DocumentID": 221,
        "DocumentName": "Your account",
        "DocumentNamePath": "/Special pages/Your account",
        "open": false,
      },
      "222": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Your-e-books",
        "DocumentChildrenIDs": [],
        "DocumentID": 222,
        "DocumentName": "Your e-books",
        "DocumentNamePath": "/Special pages/Your e-books",
        "open": false,
      },
      "224": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Store/Accessories",
        "DocumentChildrenIDs": [
          290,
          289,
          287,
          297,
          288,
          296,
        ],
        "DocumentID": 224,
        "DocumentName": "Accessories",
        "DocumentNamePath": "/Store/Accessories",
        "open": false,
      },
      "225": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Store/Brewers",
        "DocumentChildrenIDs": [
          233,
          232,
          234,
          235,
          236,
          237,
          238,
          239,
        ],
        "DocumentID": 225,
        "DocumentName": "Brewers",
        "DocumentNamePath": "/Store/Brewers",
        "open": false,
      },
      "226": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Store/Coffee",
        "DocumentChildrenIDs": [
          271,
          272,
          273,
          274,
          275,
          276,
          277,
          278,
          279,
        ],
        "DocumentID": 226,
        "DocumentName": "Coffee",
        "DocumentNamePath": "/Store/Coffee",
        "open": false,
      },
      "227": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Store/E-books",
        "DocumentChildrenIDs": [
          280,
          281,
        ],
        "DocumentID": 227,
        "DocumentName": "E-books",
        "DocumentNamePath": "/Store/E-books",
        "open": false,
      },
      "228": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Store/Grinders",
        "DocumentChildrenIDs": [
          282,
          292,
          291,
          283,
          284,
          285,
          293,
        ],
        "DocumentID": 228,
        "DocumentName": "Grinders",
        "DocumentNamePath": "/Store/Grinders",
        "open": false,
      },
      "229": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Special-pages/Privacy",
        "DocumentChildrenIDs": [],
        "DocumentID": 229,
        "DocumentName": "Privacy",
        "DocumentNamePath": "/Special pages/Privacy",
        "open": false,
      },
      "231": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Store/Coffee-Azure",
        "DocumentChildrenIDs": [],
        "DocumentID": 231,
        "DocumentName": "Coffee - Azure",
        "DocumentNamePath": "/Store/Coffee - Azure",
        "open": false,
      },
      "240": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/Australia/Brisbane",
        "DocumentChildrenIDs": [],
        "DocumentID": 240,
        "DocumentName": "Brisbane",
        "DocumentNamePath": "/Cafes/Australia/Brisbane",
        "open": false,
      },
      "242": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/Australia/Melbourne",
        "DocumentChildrenIDs": [],
        "DocumentID": 242,
        "DocumentName": "Melbourne",
        "DocumentNamePath": "/Cafes/Australia/Melbourne",
        "open": false,
      },
      "244": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/Australia/Sydney",
        "DocumentChildrenIDs": [],
        "DocumentID": 244,
        "DocumentName": "Sydney ",
        "DocumentNamePath": "/Cafes/Australia/Sydney ",
        "open": false,
      },
      "246": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/Europe/Amsterdam",
        "DocumentChildrenIDs": [],
        "DocumentID": 246,
        "DocumentName": "Amsterdam",
        "DocumentNamePath": "/Cafes/Europe/Amsterdam",
        "open": false,
      },
      "248": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/Europe/Birmingham",
        "DocumentChildrenIDs": [],
        "DocumentID": 248,
        "DocumentName": "Birmingham ",
        "DocumentNamePath": "/Cafes/Europe/Birmingham ",
        "open": false,
      },
      "250": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/Europe/Liverpool",
        "DocumentChildrenIDs": [],
        "DocumentID": 250,
        "DocumentName": "Liverpool",
        "DocumentNamePath": "/Cafes/Europe/Liverpool",
        "open": false,
      },
      "252": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/Europe/London",
        "DocumentChildrenIDs": [],
        "DocumentID": 252,
        "DocumentName": "London ",
        "DocumentNamePath": "/Cafes/Europe/London ",
        "open": false,
      },
      "254": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/Europe/Madrid",
        "DocumentChildrenIDs": [],
        "DocumentID": 254,
        "DocumentName": "Madrid ",
        "DocumentNamePath": "/Cafes/Europe/Madrid ",
        "open": false,
      },
      "256": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/North-America/Boston",
        "DocumentChildrenIDs": [],
        "DocumentID": 256,
        "DocumentName": "Boston",
        "DocumentNamePath": "/Cafes/North America/Boston",
        "open": false,
      },
      "259": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/North-America/Chicago",
        "DocumentChildrenIDs": [],
        "DocumentID": 259,
        "DocumentName": "Allendale",
        "DocumentNamePath": "/Cafes/North America/Allendale",
        "open": false,
      },
      "260": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/North-America/Los-Angeles",
        "DocumentChildrenIDs": [],
        "DocumentID": 260,
        "DocumentName": "Los Angeles",
        "DocumentNamePath": "/Cafes/North America/Los Angeles",
        "open": false,
      },
      "262": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/North-America/New-York",
        "DocumentChildrenIDs": [],
        "DocumentID": 262,
        "DocumentName": "New York",
        "DocumentNamePath": "/Cafes/North America/New York",
        "open": false,
      },
      "264": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/North-America/Ottawa",
        "DocumentChildrenIDs": [],
        "DocumentID": 264,
        "DocumentName": "Ottawa",
        "DocumentNamePath": "/Cafes/North America/Ottawa",
        "open": false,
      },
      "266": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Cafes/North-America/Toronto",
        "DocumentChildrenIDs": [],
        "DocumentID": 266,
        "DocumentName": "Toronto",
        "DocumentNamePath": "/Cafes/North America/Toronto",
        "open": false,
      },
      "268": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Store/Checkout/Billing-and-Delivery",
        "DocumentChildrenIDs": [],
        "DocumentID": 268,
        "DocumentName": "Billing & Delivery",
        "DocumentNamePath": "/Store/Checkout/Billing & Delivery",
        "open": false,
      },
      "269": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Store/Checkout/Review",
        "DocumentChildrenIDs": [],
        "DocumentID": 269,
        "DocumentName": "Review",
        "DocumentNamePath": "/Store/Checkout/Review",
        "open": false,
      },
      "270": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Store/Checkout/Shopping-cart",
        "DocumentChildrenIDs": [],
        "DocumentID": 270,
        "DocumentName": "Shopping cart",
        "DocumentNamePath": "/Store/Checkout/Shopping cart",
        "open": false,
      },
      "286": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Colombia/America-s-coffee-poster.aspx",
        "DocumentChildrenIDs": [],
        "DocumentID": 286,
        "DocumentName": "America-s-coffee-poster",
        "DocumentNamePath": "/Campaign assets/Café promotion/America-s-coffee-poster",
        "open": false,
      },
      "294": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Colombia",
        "DocumentChildrenIDs": [
          298,
        ],
        "DocumentID": 294,
        "DocumentName": "Colombia",
        "DocumentNamePath": "/Campaign assets/Café promotion/Colombia",
        "open": false,
      },
      "295": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Colombia/Thank-you",
        "DocumentChildrenIDs": [],
        "DocumentID": 295,
        "DocumentName": "Thank you",
        "DocumentNamePath": "/Campaign assets/Café promotion/Thank you",
        "open": false,
      },
      "298": {
        "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/Campaign-assets/Cafe-promotion/Colombia/Colombia-B-variant",
        "DocumentChildrenIDs": [],
        "DocumentID": 298,
        "DocumentName": "Colombia B variant",
        "DocumentNamePath": "/Campaign assets/Café promotion/Colombia/Colombia B variant",
        "open": false,
      },
    },
  notPublishedPages: {
    "299": {
      "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/BasicWorkflowPaga",
      "DocumentID": 299,
      "DocumentName": "BasicWorkflowPaga",
      "DocumentNamePath": "/BasicWorkflowPaga",
      "NextWorkflowSteps": [
        {
          "WorkflowStepDisplayName": "Magistersky step",
          "WorkflowStepID": 5903,
        },
      ],
      "PreviousWorkflowSteps": [
        {
          "WorkflowStepDisplayName": "Edit",
          "WorkflowStepID": 5899,
        },
      ],
    },
    "300": {
      "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/AdvancedWorkflowPaga",
      "DocumentID": 300,
      "DocumentName": "AdvancedWorkflowPaga",
      "DocumentNamePath": "/AdvancedWorkflowPaga",
      "NextWorkflowSteps": [],
      "PreviousWorkflowSteps": [
        {
          "WorkflowStepDisplayName": "Bakalarsky lavy krok",
          "WorkflowStepID": 5907,
        },
        {
          "WorkflowStepDisplayName": "Edit",
          "WorkflowStepID": 5904,
        },
      ],
    },
  },
  selectedPage: {
    "AbsoluteURL": "https://matusmkenticopages.azurewebsites.net/",
    "DocumentChildrenIDs": [
      300,
      299,
      163,
      167,
      157,
      155,
      159,
      161,
      165,
      154,
      152,
    ],
    "DocumentID": 150,
    "DocumentName": "",
    "DocumentNamePath": "/",
    "open": true,
  },
};

export default (state = INIT_STATE, { type, payload }) => {
  switch (type) {
    case PAGES_TOGGLE_SUBITEMS:
      return {
        ...state,
        publishedPages: {
          ...state.publishedPages,
          [payload]: {
            ...state.publishedPages[payload],
            open: !state.publishedPages[payload].open || false,
          },
        },
      };
    case PAGES_SAVE_PAGES:
      console.log(payload.notPublishedPages);
      return { ...state, ...payload };
    case PAGES_SELECT_PAGE:
      return { ...state, selectedPage: payload };
    default:
      return state;
  }
};
